module GistUpload
  def self.handle(filename, content)
    print "Upload to Gist? (y/n): "
    gist = gets.chomp

    if %w|y yes|.include?(gist.downcase)
      uri = URI.parse("https://api.github.com/gists")

      request = Net::HTTP::Post.new(uri.path, { 'Content-Type' => 'application/json' })
      request.body = {
        :description => "CSV Generated by #{`whoami`} from #{SCRIPT}.",
        :public => false,
        :files => {
          filename => { content: content }
        }
      }.to_json

      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true

      response = http.request(request)
      body = JSON.parse(response.body)

      url = body["html_url"]
      puts "Uploaded to gist: #{url}"
      system("open #{url}")
    end
  end
end
